import Navigation from "./components/navigation"
import styles from "./styles/layout.module.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={styles.layout}>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
